/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alisson Jaques
 */
public class TelaRelatorioPedido extends javax.swing.JFrame {

    private ArrayList<String> corredor;
    private ArrayList<String> receptaculo;
    private ArrayList<String> codigoProduto;
    private ArrayList<String> codigoUPC;
    
    /**
     * Creates new form TelaRelatorioPedido
     */
    public TelaRelatorioPedido(ArrayList<String> corredor, ArrayList<String> receptaculo, ArrayList<String> codigoProduto, ArrayList<String> codigoUPC) {
        this.corredor = corredor;
        this.receptaculo = receptaculo;
        this.codigoProduto = codigoProduto;
        this.codigoUPC = codigoUPC;
        initComponents();
    }
    
    public void preencherRelatorio() {
        DefaultTableModel model = (DefaultTableModel) getTabelaRelatorioPedido().getModel();
        int i = 0;
        for (String corredor : getCorredor()) {
            model.addRow(new Object[]{corredor,getReceptaculo().get(i),getCodigoProduto().get(i),getCodigoUPC().get(i)});
            i++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelatorioPedido = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Busca Pedido");
        setResizable(false);

        tabelaRelatorioPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Corredor", "Receptáculo", "Código da Peça", "Código UPC da Peça"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaRelatorioPedido);
        if (tabelaRelatorioPedido.getColumnModel().getColumnCount() > 0) {
            tabelaRelatorioPedido.getColumnModel().getColumn(0).setMinWidth(25);
            tabelaRelatorioPedido.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaRelatorioPedido.getColumnModel().getColumn(1).setMinWidth(30);
            tabelaRelatorioPedido.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaRelatorioPedido;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the corredor
     */
    public ArrayList<String> getCorredor() {
        return corredor;
    }

    /**
     * @param corredor the corredor to set
     */
    public void setCorredor(ArrayList<String> corredor) {
        this.corredor = corredor;
    }

    /**
     * @return the receptaculo
     */
    public ArrayList<String> getReceptaculo() {
        return receptaculo;
    }

    /**
     * @param receptaculo the receptaculo to set
     */
    public void setReceptaculo(ArrayList<String> receptaculo) {
        this.receptaculo = receptaculo;
    }

    /**
     * @return the codigoProduto
     */
    public ArrayList<String> getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * @param codigoProduto the codigoProduto to set
     */
    public void setCodigoProduto(ArrayList<String> codigoProduto) {
        this.codigoProduto = codigoProduto;
    }

    /**
     * @return the codigoUPC
     */
    public ArrayList<String> getCodigoUPC() {
        return codigoUPC;
    }

    /**
     * @param codigoUPC the codigoUPC to set
     */
    public void setCodigoUPC(ArrayList<String> codigoUPC) {
        this.codigoUPC = codigoUPC;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the tabelaRelatorioPedido
     */
    public javax.swing.JTable getTabelaRelatorioPedido() {
        return tabelaRelatorioPedido;
    }

    /**
     * @param tabelaRelatorioPedido the tabelaRelatorioPedido to set
     */
    public void setTabelaRelatorioPedido(javax.swing.JTable tabelaRelatorioPedido) {
        this.tabelaRelatorioPedido = tabelaRelatorioPedido;
    }
}
